// <auto-generated />
using IF.Plugins.EFCoreSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IF.Plugins.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(IFContext))]
    [Migration("20260823182656_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IF.CoreBusiness.Instruction", b =>
                {
                    b.Property<int>("InstructionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionID"));

                    b.Property<string>("InstructionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfRelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructionID");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("IF.CoreBusiness.Machine", b =>
                {
                    b.Property<int>("MachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineID"));

                    b.Property<string>("MachineDW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineID");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("IF.CoreBusiness.Part", b =>
                {
                    b.Property<int>("PartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartID"));

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartID");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("InstructionMachine", b =>
                {
                    b.Property<int>("InstructionsInstructionID")
                        .HasColumnType("int");

                    b.Property<int>("MachinesMachineID")
                        .HasColumnType("int");

                    b.HasKey("InstructionsInstructionID", "MachinesMachineID");

                    b.HasIndex("MachinesMachineID");

                    b.ToTable("InstructionMachine", (string)null);
                });

            modelBuilder.Entity("InstructionPart", b =>
                {
                    b.Property<int>("InstructionsInstructionID")
                        .HasColumnType("int");

                    b.Property<int>("PartsPartID")
                        .HasColumnType("int");

                    b.HasKey("InstructionsInstructionID", "PartsPartID");

                    b.HasIndex("PartsPartID");

                    b.ToTable("InstructionPart", (string)null);
                });

            modelBuilder.Entity("InstructionMachine", b =>
                {
                    b.HasOne("IF.CoreBusiness.Instruction", null)
                        .WithMany()
                        .HasForeignKey("InstructionsInstructionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IF.CoreBusiness.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachinesMachineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstructionPart", b =>
                {
                    b.HasOne("IF.CoreBusiness.Instruction", null)
                        .WithMany()
                        .HasForeignKey("InstructionsInstructionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IF.CoreBusiness.Part", null)
                        .WithMany()
                        .HasForeignKey("PartsPartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
